### ISSUE TITLE
yosemite上面没有libncursesw.5.dylib

### ISSUE THREAD

**Issue by zqy117** [happypeter/happygrep#15]
在哪里下载libncursesw.5.dylib 我没有找到~~多谢

**Comment by simbazz** [comment]
I got the same error on my Mac OS X 10.9 . Here I got the solution: http://stackoverflow.com/questions/29025815/happygrep-dyld-library-not-loaded-usr-local-opt-ncurses-lib-libncursesw-5-d/29025968#29025968

**Comment by happypeter** [comment]
@simbazz Thx

**Comment by happypeter** [comment]
https://github.com/happypeter/happygrep/commit/ac4da107fb56c46956d86fc10c7bbe2bb1423a4d

Yosemite 的安装解决了。

**Comment by zqy117** [comment]
多谢。
