### ISSUE TITLE
不知道这个是不是内存问题

### ISSUE THREAD

**Issue by wjcgithub** [happypeter/happygrep#17]
[RPathN]     xxx: happygrep.c:993: navigate_view: Assertion `0 <= view->lineno && view->lineno < view->lines' failed.
already at first line                                                                                                已放弃 (核心已转储)

**Comment by wjcgithub** [comment]
忘记执行的command了， 就是数据量大会有这个问题是吗？

**Comment by happypeter** [comment]
数据量大的时候会出现崩溃现象的。
