### ISSUE TITLE
MAKE时出现错误

### ISSUE THREAD

**Issue by cckoo** [happypeter/happygrep#18]
[root@dfrz-virtual-machine happygrep-master]#make
gcc happygrep.c -o happygrep -lncursesw
/tmp/cckqFXS3.o: In function `main':
happygrep.c:(.text+0x633): undefined reference to `libiconv_open'
happygrep.c:(.text+0x692): undefined reference to `libiconv_open'
collect2: ld 返回 1
make: *** [all] 错误 1

**Comment by cckoo** [comment]
MAKE出现问题

**Comment by happypeter** [comment]
操作系统是 ubuntu 吗？

试试

    sudo apt-get install libiconv

**Comment by cckoo** [comment]
是的，我使用apt-get 发现找不到这个包，于是我自己去网上下了一个源码安装了，但是好像还是不行
下的是这个版本的libiconv-1.14.tar.gz，是因为版本不对吗

**Comment by happypeter** [comment]
我在我的 ubuntu 14.04 系统上安装了一下，完全按照  README 中的步骤就可以的。你的版本是？

**Comment by cckoo** [comment]
我的是Ubuntu12.04，不知道是不是我之前弄了很多环境，还把系统的源给换了才这样，不然我再安装一个纯净版先试下好了，谢谢老师

**Comment by cckoo** [comment]
我的是Ubuntu12.04，不知道是不是我之前弄了很多环境，还把系统的源给换了才这样，不然我再安装一个纯净版先试下好了，谢谢老师

**Comment by cckoo** [comment]
我的是Ubuntu12.04，不知道是不是我之前弄了很多环境，还把系统的源给换了才这样，不然我再安装一个纯净版先试下好了，谢谢老师

**Comment by happypeter** [comment]
just try
