### ISSUE TITLE
Ubuntu安装后怎么使用啊

### ISSUE THREAD

**Issue by iblueer** [happypeter/happygrep#19]
根据README.md的指导完成了安装，目前程序在~/bin/xxx目录下存在。请问这个xxx是什么？可替代否？
下面那个命令中的xxx呢？也可替代否？现在完全是无法使用的情况中，求指导。

**Comment by happypeter** [comment]
`xxx` 是可执行文件的名字，当然改成任何名字都可以的。

使用方法：

```
cd project/
xxx keyword
```

**Comment by iblueer** [comment]
恩，我的确是这么做的，但是系统提示找不到命令xxx。这个就让我感到很不解了。我是Ubuntu的64位14.04LTS版本。来自我的华为手机-------- 原始邮件 --------主题：Re: [happygrep] Ubuntu安装后怎么使用啊 (#19)发件人：Peter Wang 收件人：happypeter/happygrep 抄送：Maemolee xxx 是可执行文件的名字，当然改成任何名字都可以的。

使用方法：

cd project/
xxx keyword

**Comment by happypeter** [comment]
需要导出一下 PATH ，到 .bashrc 中，添加

```
export PATH=~/bin:$PATH
```

然后，保存退出

```
source .bashrc
```

就可以找到这个命令了。

看来您的 Linux 基础知识还是需要补一补，推荐：http://www.imooc.com/learn/181

**Comment by iblueer** [comment]
谢谢您的指导，我的确是正在学习您的这套课程，感觉获益匪浅。来自我的华为手机-------- 原始邮件 --------主题：Re: [happygrep] Ubuntu安装后怎么使用啊 (#19)发件人：Peter Wang 收件人：happypeter/happygrep 抄送：Maemolee 需要导出一下 PATH ，到 .bashrc 中，添加

export PATH=~/bin:$PATH


然后，保存退出

source .bashrc


就可以找到这个命令了。

看来您的 Linux 基础知识还是需要补一补，推荐：http://www.imooc.com/learn/181
